name: Build QEMU Screamer

on:
  push:
    branches:
      - screamer

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Install Required Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential zlib1g-dev libglib2.0-dev libpixman-1-dev git
        
    - name: Clone Repository
      run: git clone -b screamer https://github.com/mcayland/qemu qemu-screamer
      
    - name: Configure and Build
      run: |
        cd qemu-screamer
        ./configure --target-list="ppc-softmmu" --enable-gtk --enable-sdl --audio-drv-list="pa" --enable-vde
        make -j $(nproc)
      
    - name: Strip Debug Symbols
      run: strip qemu-screamer/build/qemu-system-ppc
      
    - name: Archive Executable
      uses: actions/upload-artifact@v2
      with:
        name: qemu-executable
        path: qemu-screamer/build/qemu-system-ppc
