name: Build QEMU Screamer Fork

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true

    - name: Install dependencies using script
      run: |
        msys2_shell.cmd -defterm -no-start -mingw64 -c "cd $GITHUB_WORKSPACE && ./install-packages.sh"

    - name: Clone Screamer branch of QEMU
      run: |
        msys2_shell.cmd -defterm -no-start -mingw64 -c "git clone -b screamer https://github.com/mcayland/qemu qemu-screamer"

    - name: Configure QEMU
      run: |
        msys2_shell.cmd -defterm -no-start -mingw64 -c "cd qemu-screamer && ./configure --target-list='ppc-softmmu' --enable-gtk --enable-sdl --audio-drv-list='pa' --enable-vde"

    - name: Compile QEMU
      run: |
        msys2_shell.cmd -defterm -no-start -mingw64 -c "cd qemu-screamer && make -j $(nproc)"

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: qemu-screamer-build
        path: qemu-screamer/build
