name: Build QEMU PPC Screamer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.6  # Updated to the specific version

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git libglib2.0-dev libfdt-dev libpixman-1-dev zlib1g-dev ninja-build

      - name: Configure QEMU
        run: ./configure --target-list=ppc-softmmu

      - name: Build QEMU
        run: make -j$(nproc)

      - name: Verify build
        run: file ppc-softmmu/qemu-system-ppc
