name: Build QEMU PPC Screamer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.6

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git libglib2.0-dev libfdt-dev libpixman-1-dev zlib1g-dev meson ninja-build

      - name: Initialize and update submodules
        run: git submodule update --init --recursive

      - name: Create build directory
        run: mkdir -p build

      - name: Configure QEMU with Meson
        run: meson setup build --cross-file ppc-softmmu

      - name: Build QEMU with Ninja
        run: ninja -C build

      - name: Verify build
        run: file build/qemu-system-ppc
